issues:
  # exclude-use-default: false
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0013
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments

linters:
  enable:
    - revive
    - gofmt
    - goimports
    - asasalint
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - makezero
    - reassign

linters-settings:
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
